"""Build Birds/screening.csv: per-paper assessment of the 50 most recent Birds papers.
Scores:  s_data/s_time/s_ease in 0-5, s_figs = figure count capped at 10.
score = 0.4*s_data + 0.3*s_time + 0.2*s_ease + 0.1*s_figs   (same weighting as Seeds/Analytica)"""
import pandas as pd

# article -> (data_availability, data_location, data_size, original_method,
#             reproduction_difficulty, new_method_idea, novelty, beat_feasibility,
#             s_data, s_time, s_ease)
A = {
55: ("public (MDPI supplement: full reproducibility package, SHA256-verified)",
     "supp s001.zip / Riccordia_maugaeus_reproducibility_package: 3 derived CSVs (91,677 rows) + R scripts + GEE scripts + SRTM GeoTIFF + validation_targets.csv + SHA256SUMS.txt",
     "61 MB unpacked; 91,677 x 12 checklist table (89,682 in 2013-2025)",
     "binomial GLM (logit) on checklist reporting + dynamic multi-season occupancy (unmarked::colext)",
     "easy - derived model-ready CSVs, author R scripts, author validation targets",
     "detection-disentangled deep model: effort/occupancy factorised head, multi-scale spatial Fourier features, missingness-native NDVI (uses all 89,682 not 68,976), spatial-block invariance penalty, GBDT+NN teacher ensemble distilled to one student",
     "high", "high (large N, weak linear-logit baseline, 23% of data discarded by original)", 5, 5, 5),
56: ("public (Mendeley Data, HTTP 200)", "doi:10.17632/mtykttfn6x.1", "not downloaded (rank 2)",
     "bipartite plant-hummingbird network metrics + rewiring decomposition", "medium (network null models)",
     "graph neural network / latent-space interaction model", "medium", "plausible", 5, 4, 3),
45: ("public (Mendeley Data, HTTP 200; data + R code)", "doi:10.17632/9gd2sbdg43", "not downloaded (rank 3)",
     "predation-rate GLMM on sentinel prey across time/space", "medium",
     "spatiotemporal hierarchical model / gradient boosting", "medium", "plausible", 5, 4, 3),
19: ("public (Mendeley Data, HTTP 200)", "doi:10.17632/jy3vsv66wp.1", "not downloaded; small (behavioural trials)",
     "LMM on exploration/learning assays by migratory status", "easy but very small N",
     "Bayesian multilevel measurement model", "low-medium", "limited by tiny N", 4, 4, 4),
17: ("public (Dryad, HTTP 200) for recovery data; biometrics on request",
     "doi:10.5061/dryad.70rxwdc8m", "not downloaded; ringing-recovery table",
     "CJS mark-recapture survival models (MARK/RMark)", "medium (capture histories)",
     "neural survival / HMM with covariates", "medium", "plausible but partial data", 4, 3, 3),
49: ("public (GitHub, HTTP 200)", "github.com/carevicunap/data-nesting-behaviour", "not downloaded; small nest-camera logs",
     "descriptive incubation-bout statistics", "easy but small",
     "change-point / HSMM bout segmentation", "low-medium", "few metrics to beat", 4, 4, 4),
25: ("public (Zenodo, HTTP 200)", "zenodo.org/records/14498854", "not downloaded; small necropsy table",
     "descriptive mortality causes", "easy but small", "none compelling", "low", "n/a", 4, 4, 4),
41: ("in article + Supplementary (source_data.zip, tracks&magpies.zip present on disk)",
     "supp s001: source_data.zip + tracks&magpies.zip", "small grid/occurrence tables",
     "range-expansion grid occupancy / spread rate", "medium", "spatial spread SDM", "medium", "plausible", 4, 3, 3),
52: ("nominally public but NOT retrievable (ResearchGate DOI returns HTTP 403, login-walled)",
     "doi:10.13140/RG.2.2.14134.66885", "inaccessible", "crop-composition optimisation for shrike territories",
     "blocked - data not downloadable", "-", "-", "n/a (data unreachable)", 1, 2, 2),
21: ("stated public but DOI DEAD (Zenodo 10.5281/zenodo.18099828 returns HTTP 404)",
     "doi:10.5281/zenodo.18099828", "inaccessible", "playback experiment on mobbing calls",
     "blocked - data not downloadable", "-", "-", "n/a (data unreachable)", 1, 3, 3),
13: ("partly public: nesting data on request; only Copernicus habitat layers are open",
     "Copernicus (public) + nesting data on request", "habitat rasters only",
     "nest-success GLM + habitat-change mapping", "blocked for the response variable", "-", "low", "n/a", 2, 3, 3),
11: ("in article + Supplementary xlsx (Tables S1-)", "supp s001: birds-4121822-supplementary.xlsx",
     "small heavy-metal concentration table", "PERMANOVA / multivariate ordination of metal loads",
     "easy but small", "hierarchical multivariate model", "low-medium", "few metrics, small N", 3, 4, 4),
16: ("Supplementary xlsx", "supp s001 xlsx", "single-tree visit log", "GLM of bird visits to one tree",
     "easy but very small", "-", "low", "n/a", 3, 4, 4),
54: ("Supplementary xlsx (Tables S1-S2: haplotypes)", "supp s001: Table S1.xlsx, Table S2.xlsx",
     "haplotype/sequence tables", "mtDNA haplotype network + phylogeography", "medium (needs GenBank pull)",
     "phylogeographic model", "low-medium", "n/a", 3, 3, 3),
15: ("Supplementary: QIIME2 .qzv artefacts + 3 xlsx", "supp s001: feature-table.qzv, taxonomy.qzv, TS1-3.xlsx",
     "microbiome visualisations (not raw reads)", "16S amplicon diversity analysis",
     "medium; raw reads not in package", "microbiome deep learning", "medium", "raw reads missing", 3, 3, 2),
40: ("Supplementary xlsx (diet matrix)", "supp s001 xlsx", "owl diet matrix",
     "diet-diversity indices across 9 owl species", "easy", "multivariate diet niche model", "low-medium", "plausible but few metrics", 3, 4, 4),
39: ("Supplementary pdf (7 tables)", "supp s001 pdf", "winter count trends in PDF only",
     "long-term population trend models", "hard - tables locked in PDF", "-", "low", "n/a", 2, 3, 2),
18: ("Supplementary pdf", "supp s001 pdf", "wing morphometrics in PDF", "wing-shape morphometrics",
     "hard - PDF only", "-", "low", "n/a", 2, 3, 2),
14: ("Supplementary pdf", "supp s001 pdf", "PDF tables", "pika/yak grazing effects on birds", "hard - PDF only", "-", "low", "n/a", 2, 3, 2),
37: ("NOT public - raw data on request; supplement is only Figure S1 + Table S1 as PDF",
     "supp s001: Figure S1.pdf, Table S1.pdf", "none retrievable",
     "basic ML (regression/classification) on pigeon flight-performance data",
     "blocked - no raw data despite being an ML paper", "modern tabular ML", "medium", "impossible without data", 0, 3, 3),
38: ("Supplementary pdf", "supp s001 pdf", "mitogenome annotation", "mitogenome assembly + phylogeny", "medium (GenBank)", "-", "low", "n/a", 2, 2, 2),
46: ("Supplementary pdf", "supp s001 pdf", "flock composition tables", "mixed-species flock seasonality", "hard - PDF only", "-", "low", "n/a", 2, 3, 3),
51: ("Supplementary: audio wav + spectrogram png + PDF table", "supp s001: Audio S1-S2.wav, Figure S1-S2.png, Table S1.pdf",
     "2 audio files + PDF", "distance-sampling density estimation for Black Rail", "partial - detection data not tabulated",
     "bioacoustic CNN", "medium", "insufficient audio (2 files)", 2, 3, 2),
60: ("in article/Supplementary pdf (qualitative ethnography)", "supp s001 pdf", "interview transcripts not released",
     "qualitative ethnographic coding", "not applicable to quantitative benchmarking", "-", "low", "n/a", 1, 2, 2),
59: ("on request (data-owner restriction)", "none", "-", "LMM on ringing recaptures / body condition", "blocked", "-", "low", "n/a", 1, 3, 3),
58: ("on request", "none", "-", "louse prevalence survey", "blocked", "-", "low", "n/a", 1, 3, 3),
57: ("on request (Movebank mentioned but no accession)", "none", "-", "GPS tracking home-range analysis", "blocked", "-", "medium", "n/a", 1, 3, 3),
53: ("on request", "none", "-", "review/case reports of colour aberrations", "blocked", "-", "low", "n/a", 1, 3, 3),
50: ("on request", "none", "-", "review of UV sensitivity pathways", "review", "-", "low", "n/a", 0, 2, 2),
48: ("on request", "none", "-", "diet composition of Rock Sparrow", "blocked", "-", "low", "n/a", 1, 3, 3),
47: ("on request", "none", "-", "Gyrfalcon breeding performance GLM", "blocked", "-", "low", "n/a", 1, 3, 3),
44: ("on request", "none", "-", "pollinator observation counts", "blocked", "-", "low", "n/a", 1, 3, 3),
43: ("stated publicly available (occurrence aggregators) but no accession given", "none given", "-",
     "invasion spread description", "unclear", "-", "low", "n/a", 2, 3, 3),
42: ("on request (social-media derived)", "none", "-", "social-media records of threatened birds", "blocked", "-", "medium", "n/a", 1, 3, 3),
36: ("on request", "none", "-", "taxonomic/historical review", "review", "-", "low", "n/a", 0, 2, 2),
35: ("xeno-canto cited (public archive) but no recording list released", "xeno-canto, no accession list", "-",
     "vocal-behaviour spectrogram analysis", "unclear - recordings not enumerated", "bioacoustic model", "medium", "n/a", 2, 3, 2),
34: ("correction notice", "none", "-", "correction to an earlier article", "not applicable", "-", "n/a", "n/a", 0, 0, 0),
33: ("on request", "none", "-", "MaxEnt climate-driven SDM", "blocked (occurrences not released)",
     "modern SDM ensemble", "medium", "n/a - no occurrences", 1, 3, 3),
32: ("on request", "none", "-", "conceptual/opinion piece", "review", "-", "low", "n/a", 0, 2, 2),
31: ("on request", "none", "-", "global distribution review of Monk Parakeet", "blocked", "-", "low", "n/a", 1, 2, 2),
30: ("on request", "none", "-", "cytogenetic karyotype characterisation", "wet lab", "-", "low", "n/a", 1, 2, 2),
29: ("on request", "none", "-", "individual specialisation in a frugivory network", "blocked", "-", "medium", "n/a", 1, 3, 3),
28: ("on request", "none", "-", "wildlife-rehab admission trends + outcome predictors", "blocked", "-", "medium", "n/a", 1, 3, 3),
27: ("on request", "none", "-", "new elevational distribution records", "descriptive", "-", "low", "n/a", 1, 3, 3),
26: ("on request", "none", "-", "review of shrike sociality", "review", "-", "low", "n/a", 0, 2, 2),
24: ("on request (historical literature)", "none", "-", "historical distribution reconstruction", "archival", "-", "low", "n/a", 1, 2, 2),
23: ("on request", "none", "-", "vigilance behaviour vs wind speed GLMM", "blocked", "-", "low", "n/a", 1, 3, 3),
22: ("on request + Supplementary pdf", "supp s001 pdf", "-", "sound propagation / predator exposure experiment", "blocked", "-", "low", "n/a", 1, 3, 3),
20: ("on request", "none", "-", "distance sampling density/abundance estimate", "blocked", "-", "low", "n/a", 1, 3, 3),
12: ("on request", "none", "-", "post-fledging dependence period analysis", "blocked", "-", "low", "n/a", 1, 3, 3),
}

raw = pd.read_csv("Birds/screen_raw.csv").set_index("article")
rows = []
for art, v in A.items():
    r = raw.loc[art]
    s_data, s_time, s_ease = v[8], v[9], v[10]
    s_figs = min(int(r.n_fig), 10)
    score = round(0.4 * s_data + 0.3 * s_time + 0.2 * s_ease + 0.1 * s_figs, 2)
    rows.append(dict(article=art, doi=r.doi, published=r.published, title=r.title,
                     type="correction" if art == 34 else ("review" if r.is_review else "article"),
                     data_availability=v[0], data_location=v[1], data_size=v[2],
                     original_method=v[3], reproduction_difficulty=v[4], new_method_idea=v[5],
                     novelty=v[6], beat_original_feasibility=v[7],
                     n_figures=int(r.n_fig), n_tables=int(r.n_tab),
                     s_data=s_data, s_time=s_time, s_ease=s_ease, s_figs=s_figs, score=score))

df = pd.DataFrame(rows).sort_values("score", ascending=False).reset_index(drop=True)
df.insert(0, "rank", range(1, len(df) + 1))
df.to_csv("Birds/screening.csv", index=False)
print(f"{len(df)} papers scored")
print(df[["rank","article","score","s_data","s_time","s_ease","s_figs","title"]].head(12).to_string(index=False, max_colwidth=58))
